/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_oct;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author amolika
 */
public class AddCashier extends javax.swing.JFrame {

    /**
     * Creates new form AddCashier
     */
    public AddCashier() {
        initComponents();
        setVisible(true);
        setSize(600,600);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(35, 44, 131, 36);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 40, 180, 40);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 140, 130, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(260, 130, 170, 50);

        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 240, 160, 40);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(260, 220, 170, 60);

        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 320, 160, 40);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 310, 170, 50);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 390, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username=jTextField1.getText();
        String pass=jPasswordField1.getText();
        String confirmPass =jPasswordField2.getText();
        String Mobile =jTextField2.getText();
        if(username.isEmpty()|| pass.isEmpty()|| confirmPass.isEmpty() || Mobile.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "All fields are required");
        }
        
        if(!pass.equals(confirmPass)){
            JOptionPane.showMessageDialog(rootPane, "password and confirm password field should contain same value");
        }
        
        if(Mobile.isEmpty()|| Mobile.length()!=10 || !Mobile.matches("[0-9]+")){
            JOptionPane.showMessageDialog(rootPane, "Please Enter a Valid mobile number");
        }
        try{
            ResultSet rs=DbLoader.executestatment("Select * from cashier where username='"+username+"'");
        if (rs.next())
        {
            JOptionPane.showMessageDialog(rootPane, "Cashier already exists");
        }
        else{
            rs.moveToInsertRow();
            rs.updateString("username",username);
            rs.updateString("password", pass);
            rs.updateString("MobileNumber", Mobile);
            rs.updateString("status", "effective");
            rs.insertRow();
            JOptionPane.showMessageDialog(rootPane, "Cashier Added Successfully");
            
        }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
