/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_oct;

import java.io.File;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author amolika
 */
public class adminAddProduct extends javax.swing.JFrame {

    /**
     * Creates new form adminAddProduct
     */
    JFileChooser chooser;
    public adminAddProduct() {
        initComponents();
     
        chooser=new JFileChooser();
        setSize(700,800);
          jComboBox1.removeAllItems();
       
        for(int i=0;i<categoryclass.category.length;i++)
        {
            
            jComboBox1.addItem(categoryclass.category[i]);
        }
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        insertphoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 160, 60);

        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 120, 40);

        jLabel3.setText("Description");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 146, 110, 30);

        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 120, 40);

        jLabel5.setText("Offer Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 270, 120, 40);

        jLabel6.setText("Photo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 330, 41, 16);
        getContentPane().add(insertphoto);
        insertphoto.setBounds(220, 330, 180, 50);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 330, 110, 50);

        jButton2.setText("submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 390, 110, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 40, 150, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 80, 150, 50);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 140, 150, 50);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(290, 210, 160, 50);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(290, 270, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String category=(String) jComboBox1.getSelectedItem();
        String productName=jTextField1.getText();
        String description=jTextField2.getText();
        String Price=jTextField3.getText();
        String OfferPrice=jTextField4.getText();
        if (category.isEmpty()|| productName.isEmpty()|| Price.isEmpty()|| OfferPrice.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane,"All fields are required.");
        }
        else{
            try{
            ResultSet rs=DbLoader.executestatment(
            "select * from products where product_name ='"+productName+"' and category='"+category+"'");
            if(rs.next())
            {
                JOptionPane.showMessageDialog(rootPane, "Product already exists");
            }
            else{
                rs.moveToInsertRow();
                rs.updateString("product_name",productName);
                rs.updateString("category",category);
                rs.updateString("description",description);
                rs.updateInt("price",Integer.parseInt(Price));
                rs.updateInt("offer_price",Integer.parseInt(OfferPrice));
                rs.updateString("photo",path);
                rs.insertRow();
                JOptionPane.showMessageDialog(rootPane,"Product added successfully");
            }
        }
            catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    String path;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int r = chooser.showOpenDialog(this);
        
        if (r == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            path=categoryclass.savefile(f.getPath());
            System.out.println(path);
            insertphoto.setText(path);
        } else {
            System.out.println("Please select file");
            insertphoto.setText("Please select a file");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminAddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel insertphoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
