             /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos_oct;

import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


/**
 *
 * @author amolika
 */
public class adminManageProducts extends javax.swing.JFrame {

    /**
     * Creates new form adminManageProducts
     */
    ArrayList<productDetail> al=new ArrayList<>();
    public adminManageProducts() {
        initComponents();
        jComboBox2.removeAllItems();
       
        for(int i=0;i<categoryclass.category.length;i++)
        {
            
            jComboBox2.addItem(categoryclass.category[i]);
        }
        setSize(800,800);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(33, 40, 195, 48);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 40, 100, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 780, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String category=(String)jComboBox2.getSelectedItem();
        if(category.isEmpty())
            JOptionPane.showMessageDialog(rootPane, "All Fields are Required");
        
        else{
            al.clear();
            try{
            ResultSet rs=DbLoader.executestatment("Select * from products where category='"+category+"'");
            while(rs.next())
            {
                int pid=rs.getInt("pid");
                int price=rs.getInt("price");
                int offer_price=rs.getInt("offer_price");
                String Tcategory=rs.getString("category");
                String pname=rs.getString("product_name");
                String description=rs.getString("description");
                String Photo=rs.getString("photo");
                
                
                tablemodel tm=new tablemodel();
                jTable1.setModel(tm);
                
                
                al.add(new productDetail(pid,price,offer_price,Tcategory,pname,description,Photo));
                
            }
                
            
            }
            catch(Exception e){
                e.printStackTrace();
            }
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    class tablemodel extends AbstractTableModel {

        String names[] = {"pid","category","product_name","description","photo","price","offer_price"};

        public int getRowCount() {
            return al.size();
        }

        public int getColumnCount() {
            return 7;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            if (columnIndex == 0) {
                return al.get(rowIndex).pid;
            } else if (columnIndex == 1) {
                return al.get(rowIndex).category;
            } else if(columnIndex==2){
                return al.get(rowIndex).pname;
            }
            else if(columnIndex==3){
                return al.get(rowIndex).description;
            }
            else if(columnIndex==4){
                return al.get(rowIndex).photo;
            }
            
            else if(columnIndex==5){
                return al.get(rowIndex).price;
            }
            
            else if(columnIndex==6){
                return al.get(rowIndex).offer_price;
            }
            return null;
        }

        public String getColumnName(int columnIndex) {
            return names[columnIndex];
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
